name: Clickstream event detection
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic for enriched click data
    defaultValue: enriched-click-data
    required: true
  - name: window_minutes
    inputType: FreeText
    description: Minutes for the rolling window to detect user behaviour
    defaultValue: 30
    required: false
  - name: output
    inputType: OutputTopic
    description: Topic to write offers
    defaultValue: special-offers
    required: true
  - name: redis_host
    inputType: Secret
    description: External Redis hostname
    defaultValue: redis_host
    required: true
  - name: redis_port
    inputType: Secret
    description: External Redis port
    defaultValue: redis_port
    required: true
  - name: redis_password
    inputType: Secret
    description: External Redis password
    defaultValue: redis_password
    required: true
  - name: redis_username
    inputType: Secret
    description: External Redis username
    defaultValue: redis_username
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: behaviour_detector.py
