name: device type
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: enriched-click-data-all-keys
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic to publish data to
    defaultValue: device-type
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
