name: Stream data from CSV
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for realtime CSV data
    defaultValue: realtime-csv-data
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
